module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      1,
      'always',
      [
        'root',
        'ci',
        'deps',
        'docs',
        'contracts',
        'deploy',
        'tools',
        'auth',
        'errors',
        'messaging',
        'resilience',
        'telemetry',
        'sdk',
        'inference-router',
        'identity',
        'governance',
        'guardrails',
        'agent-runtime',
        'registry',
        'knowledge',
        'mcp-gateway',
        'document-processing',
        'evaluation',
        'data-platform',
        'web',
      ],
    ],
  },
};
